### ISSUE TITLE
Metadata in checkfile.pl output prevents translation validation

### ISSUE THREAD

**Issue by Azeezah** [regehr/opt-fuzz#1]
It looks the decompiled code from check_file.pl sometimes contains some metadata that's preventing the translation validation.  The logs have this error: `ERROR: Only functions with identical signatures can be checked`  The validation works fine if I remove the metadata manually.  

When I ran `./check-file.pl test1.ll` this is what was in output/test1-decomp.ll:

```
; ModuleID = '<stdin>'
source_filename = "<stdin>"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
; Function Attrs: noinline norecurse nounwind readnone
define i64 @slice(i64 %rdi, i64 %rsi) local_unnamed_addr #0 {
  %1 = add i64 %rsi, %rdi
  ret i64 %1
}

attributes #0 = { noinline norecurse nounwind readnone }
```

I reduced it to this to get the validation to work:
```
define i64 @slice(i64 %rdi, i64 %rsi) local_unnamed_addr #0 {
  %1 = add i64 %rsi, %rdi
  ret i64 %1
}
```

**Comment by nunoplopes** [comment]
This is a recent change in alive-tv. We now check function & argument attributes as part of the signature check (to avoid a bunch of false positives).

**Comment by regehr** [comment]
@Azeezah can you find out which specific attribute or attributes is causing the problem?

**Comment by Azeezah** [comment]
It looks like opt is adding it.

**Comment by regehr** [comment]
Ok, I see the new code now:
```
  if (FnL->getAttributes() != FnR->getAttributes())
    return -1;
```
I can work on making alive-tv handle more cases, there's clearly some room for improvement.

but @nunoplopes could you please elaborate a bit on what problems this was solving? we don't run alive-tv on the llvm test suite, was it pranav having problems here?

**Comment by regehr** [comment]
@Azeezah I'll leave this issue open for now but I think this is best fixed in alive2.
can you please add an issue there where you show a simple function, after being processed by opt, can not be validated as refining the pre-opt version of this same function?

**Comment by regehr** [comment]
@Azeezah if you remove the two lines above from alive-tv.cpp you can move forward with your work and we'll proceed to figure out how to fix this in parallel

**Comment by Azeezah** [comment]
ok @regehr

**Comment by nunoplopes** [comment]
> Ok, I see the new code now:
> 
> ```
>   if (FnL->getAttributes() != FnR->getAttributes())
>     return -1;
> ```
> 
> I can work on making alive-tv handle more cases, there's clearly some room for improvement.
> 
> but @nunoplopes could you please elaborate a bit on what problems this was solving? we don't run alive-tv on the llvm test suite, was it pranav having problems here?

We've been using alive-tv extensively to verify dumps from clang and other tests. Adding attributes is often incorrect and we are now starting to validate them, so verification may fail.
I'll remove that code so that these files go through.
